### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by seivazi** [sunwj/scanpath#1]
Hi,

Thank you for your great work. 
Could you share the code?

BR,

**Comment by ljjsfe** [comment]
The same here. Very interested in checking the performance of the network. Looking forward to your publish. Thank you so much.

**Comment by deepseek** [comment]
@sunwj

**Comment by sunwj** [comment]
Due to the COVID-19, I cannot back to the lab. and the code will be available after I was permitted to go back.
