### ISSUE TITLE
请问什么时候公开代码呢？

### ISSUE THREAD

**Issue by KORIYN** [sunwj/scanpath#3]
你好！请问什么时候公开代码呢？看完了您的论文，想尽快实验验证一下。

不胜感激~~~
谢谢！

**Comment by sunwj** [comment]
你好，由于疫情影响，目前无法返回学校，等返校之后会上传代码

**Comment by KORIYN** [comment]
你好，我是西安电子科技大学研一的一名学生。冒昧的问一句，可不可以加一下您的QQ或者微信呀~~ 刚刚接触这个领域，想向您请教。

我的QQ：1046960908
期待您的回复~~
